//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUIMonitor.MonitorRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MonitorRef.IMonitor")]
    public interface IMonitor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitor/GetRequestToVelib", ReplyAction="http://tempuri.org/IMonitor/GetRequestToVelibResponse")]
        string GetRequestToVelib(string startTime, string endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitor/GetRequestToVelib", ReplyAction="http://tempuri.org/IMonitor/GetRequestToVelibResponse")]
        System.Threading.Tasks.Task<string> GetRequestToVelibAsync(string startTime, string endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitor/GetRequestFromClient", ReplyAction="http://tempuri.org/IMonitor/GetRequestFromClientResponse")]
        string GetRequestFromClient(string startTime, string endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitor/GetRequestFromClient", ReplyAction="http://tempuri.org/IMonitor/GetRequestFromClientResponse")]
        System.Threading.Tasks.Task<string> GetRequestFromClientAsync(string startTime, string endTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitor/GetCacheNumber", ReplyAction="http://tempuri.org/IMonitor/GetCacheNumberResponse")]
        int GetCacheNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitor/GetCacheNumber", ReplyAction="http://tempuri.org/IMonitor/GetCacheNumberResponse")]
        System.Threading.Tasks.Task<int> GetCacheNumberAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitor/GetDelay", ReplyAction="http://tempuri.org/IMonitor/GetDelayResponse")]
        string GetDelay();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMonitor/GetDelay", ReplyAction="http://tempuri.org/IMonitor/GetDelayResponse")]
        System.Threading.Tasks.Task<string> GetDelayAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMonitorChannel : GUIMonitor.MonitorRef.IMonitor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MonitorClient : System.ServiceModel.ClientBase<GUIMonitor.MonitorRef.IMonitor>, GUIMonitor.MonitorRef.IMonitor {
        
        public MonitorClient() {
        }
        
        public MonitorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MonitorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MonitorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetRequestToVelib(string startTime, string endTime) {
            return base.Channel.GetRequestToVelib(startTime, endTime);
        }
        
        public System.Threading.Tasks.Task<string> GetRequestToVelibAsync(string startTime, string endTime) {
            return base.Channel.GetRequestToVelibAsync(startTime, endTime);
        }
        
        public string GetRequestFromClient(string startTime, string endTime) {
            return base.Channel.GetRequestFromClient(startTime, endTime);
        }
        
        public System.Threading.Tasks.Task<string> GetRequestFromClientAsync(string startTime, string endTime) {
            return base.Channel.GetRequestFromClientAsync(startTime, endTime);
        }
        
        public int GetCacheNumber() {
            return base.Channel.GetCacheNumber();
        }
        
        public System.Threading.Tasks.Task<int> GetCacheNumberAsync() {
            return base.Channel.GetCacheNumberAsync();
        }
        
        public string GetDelay() {
            return base.Channel.GetDelay();
        }
        
        public System.Threading.Tasks.Task<string> GetDelayAsync() {
            return base.Channel.GetDelayAsync();
        }
    }
}
