//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VelibConsoleClient.VelibSoapRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VelibSoapRef.IVelibService")]
    public interface IVelibService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetStationsOfACity", ReplyAction="http://tempuri.org/IVelibService/GetStationsOfACityResponse")]
        string GetStationsOfACity(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetStationsOfACity", ReplyAction="http://tempuri.org/IVelibService/GetStationsOfACityResponse")]
        System.Threading.Tasks.Task<string> GetStationsOfACityAsync(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetStationInfo", ReplyAction="http://tempuri.org/IVelibService/GetStationInfoResponse")]
        string GetStationInfo(string city, string station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetStationInfo", ReplyAction="http://tempuri.org/IVelibService/GetStationInfoResponse")]
        System.Threading.Tasks.Task<string> GetStationInfoAsync(string city, string station);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetHelp", ReplyAction="http://tempuri.org/IVelibService/GetHelpResponse")]
        string GetHelp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVelibService/GetHelp", ReplyAction="http://tempuri.org/IVelibService/GetHelpResponse")]
        System.Threading.Tasks.Task<string> GetHelpAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibServiceChannel : VelibConsoleClient.VelibSoapRef.IVelibService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VelibServiceClient : System.ServiceModel.ClientBase<VelibConsoleClient.VelibSoapRef.IVelibService>, VelibConsoleClient.VelibSoapRef.IVelibService {
        
        public VelibServiceClient() {
        }
        
        public VelibServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VelibServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VelibServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetStationsOfACity(string city) {
            return base.Channel.GetStationsOfACity(city);
        }
        
        public System.Threading.Tasks.Task<string> GetStationsOfACityAsync(string city) {
            return base.Channel.GetStationsOfACityAsync(city);
        }
        
        public string GetStationInfo(string city, string station) {
            return base.Channel.GetStationInfo(city, station);
        }
        
        public System.Threading.Tasks.Task<string> GetStationInfoAsync(string city, string station) {
            return base.Channel.GetStationInfoAsync(city, station);
        }
        
        public string GetHelp() {
            return base.Channel.GetHelp();
        }
        
        public System.Threading.Tasks.Task<string> GetHelpAsync() {
            return base.Channel.GetHelpAsync();
        }
    }
}
